import "./globals.css";
import Footer from "@/components/Footer";
import { Suspense } from "react"; // Consider adding loading states

export const metadata = {
  icons: {
    icon: "/images/logo.svg", // Use absolute path
  },
  title: "Naseem Mussfah",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <div className="min-h-screen flex flex-col">
          <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          <Footer />
        </div>
      </body>
    </html>
  );
}
