import "./globals.css";
import Footer from "@/components/Footer";
import { Suspense } from "react"; // Consider adding loading states

export const metadata = {
  icons: {
    icon: "/images/logo.svg", // Use absolute path
  },
  title: "Naseem Mussfah",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <div className="">
          <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          <Footer />
        </div>
      </body>
    </html>
  );
}
